// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx3UaRVRwPa51kHqLFQxU_PVcJTWKALro',
    appId: '1:277248416918:web:b120133fddeb33e51d36b7',
    messagingSenderId: '277248416918',
    projectId: 'qrscanner-be9a4',
    authDomain: 'qrscanner-be9a4.firebaseapp.com',
    storageBucket: 'qrscanner-be9a4.appspot.com',
    measurementId: 'G-L0K0J2N68M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFB6OZyvIZ20EI8j1l5cEOj0UCxovgWEg',
    appId: '1:277248416918:android:efc769ac95189e001d36b7',
    messagingSenderId: '277248416918',
    projectId: 'qrscanner-be9a4',
    storageBucket: 'qrscanner-be9a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV8l1nTHQzKVfVPAjKL_gZhU674PVHGOU',
    appId: '1:277248416918:ios:ef9535399defb92a1d36b7',
    messagingSenderId: '277248416918',
    projectId: 'qrscanner-be9a4',
    storageBucket: 'qrscanner-be9a4.appspot.com',
    iosBundleId: 'com.example.qrScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV8l1nTHQzKVfVPAjKL_gZhU674PVHGOU',
    appId: '1:277248416918:ios:ef9535399defb92a1d36b7',
    messagingSenderId: '277248416918',
    projectId: 'qrscanner-be9a4',
    storageBucket: 'qrscanner-be9a4.appspot.com',
    iosBundleId: 'com.example.qrScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx3UaRVRwPa51kHqLFQxU_PVcJTWKALro',
    appId: '1:277248416918:web:b24e959029305a391d36b7',
    messagingSenderId: '277248416918',
    projectId: 'qrscanner-be9a4',
    authDomain: 'qrscanner-be9a4.firebaseapp.com',
    storageBucket: 'qrscanner-be9a4.appspot.com',
    measurementId: 'G-LC5SRRMXEG',
  );
}
